apiVersion: v1
kind: Service
metadata:
  name: crud-demo
  namespace: crud-demo
  labels:
    app: crud-demo
spec:
  type: LoadBalancer
  selector:
    app: crud-demo
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
